name: CI Build

on:
  pull_request:
    branches: [ '*' ]
    paths:
    - "src/**"
    - ".github/workflows/ci-build.yml"

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      working-directory: ./
      ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn
      working-directory: ${{env.working-directory}}
    - name: Retrieve package version
      run: |
        echo ::set-env name=PACKAGE_VERSION::$(node scripts/version.js)
      working-directory: ${{env.working-directory}}
    - name: Build App
      run: |
        yarn build
      working-directory: ${{env.working-directory}}
    - uses: actions/upload-artifact@master
      with:
        name: app-${{env.PACKAGE_VERSION}}
        path: .next
